// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'services/chunk_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6495605399055199251),
    name: 'ChunkEntity',
    lastPropertyId: const obx_int.IdUid(11, 5503302764663213930),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2053506721480029390),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 776201475166577534),
        name: 'chunkId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 3341012522521387720),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4589742687433118403),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5034635291701800641),
        name: 'source',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 456020796288999031),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5739247315297727514),
        name: 'sectionPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1453133337069716301),
        name: 'sourceType',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 4474713933602308041),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3214372249488119725),
        name: 'packId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 7172513746426252228),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 103995594977602351),
        name: 'dlcId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7263063888200955009),
        name: 'docId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8824084892876154654),
        name: 'embeddingModelVersion',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5503302764663213930),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(5, 5237315006653595933),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384, distanceType: 2),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 6495605399055199251),
    lastIndexId: const obx_int.IdUid(5, 5237315006653595933),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ChunkEntity: obx_int.EntityDefinition<ChunkEntity>(
      model: _entities[0],
      toOneRelations: (ChunkEntity object) => [],
      toManyRelations: (ChunkEntity object) => {},
      getId: (ChunkEntity object) => object.id,
      setId: (ChunkEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ChunkEntity object, fb.Builder fbb) {
        final chunkIdOffset = fbb.writeString(object.chunkId);
        final textOffset = fbb.writeString(object.text);
        final sourceOffset = fbb.writeString(object.source);
        final sectionPathOffset = object.sectionPath == null
            ? null
            : fbb.writeString(object.sectionPath!);
        final sourceTypeOffset = fbb.writeString(object.sourceType);
        final packIdOffset = fbb.writeString(object.packId);
        final dlcIdOffset = object.dlcId == null
            ? null
            : fbb.writeString(object.dlcId!);
        final docIdOffset = object.docId == null
            ? null
            : fbb.writeString(object.docId!);
        final embeddingModelVersionOffset = object.embeddingModelVersion == null
            ? null
            : fbb.writeString(object.embeddingModelVersion!);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, chunkIdOffset);
        fbb.addOffset(2, textOffset);
        fbb.addOffset(3, sourceOffset);
        fbb.addOffset(4, sectionPathOffset);
        fbb.addOffset(5, sourceTypeOffset);
        fbb.addOffset(6, packIdOffset);
        fbb.addOffset(7, dlcIdOffset);
        fbb.addOffset(8, docIdOffset);
        fbb.addOffset(9, embeddingModelVersionOffset);
        fbb.addOffset(10, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final chunkIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sourceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final sectionPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final sourceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final packIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final dlcIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final docIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final embeddingModelVersionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final object = ChunkEntity(
          id: idParam,
          chunkId: chunkIdParam,
          text: textParam,
          source: sourceParam,
          sectionPath: sectionPathParam,
          sourceType: sourceTypeParam,
          packId: packIdParam,
          dlcId: dlcIdParam,
          docId: docIdParam,
          embeddingModelVersion: embeddingModelVersionParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChunkEntity] entity fields to define ObjectBox queries.
class ChunkEntity_ {
  /// See [ChunkEntity.id].
  static final id = obx.QueryIntegerProperty<ChunkEntity>(
    _entities[0].properties[0],
  );

  /// See [ChunkEntity.chunkId].
  static final chunkId = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[1],
  );

  /// See [ChunkEntity.text].
  static final text = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[2],
  );

  /// See [ChunkEntity.source].
  static final source = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[3],
  );

  /// See [ChunkEntity.sectionPath].
  static final sectionPath = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[4],
  );

  /// See [ChunkEntity.sourceType].
  static final sourceType = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[5],
  );

  /// See [ChunkEntity.packId].
  static final packId = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[6],
  );

  /// See [ChunkEntity.dlcId].
  static final dlcId = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[7],
  );

  /// See [ChunkEntity.docId].
  static final docId = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[8],
  );

  /// See [ChunkEntity.embeddingModelVersion].
  static final embeddingModelVersion = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[9],
  );

  /// See [ChunkEntity.embedding].
  static final embedding = obx.QueryHnswProperty<ChunkEntity>(
    _entities[0].properties[10],
  );
}
